<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Suite]" duration-ms="21784" started-at="2019-12-25T05:20:48Z" finished-at="2019-12-25T05:21:10Z">
    <groups>
    </groups>
    <test name="Test(failed)" duration-ms="21784" started-at="2019-12-25T05:20:48Z" finished-at="2019-12-25T05:21:10Z">
      <class name="com.inetBankingV1.testcases.TC_AddCustomer_003">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.inetBankingV1.testcases.TC_AddCustomer_003@dd8ba08]" name="setUp" is-config="true" duration-ms="13786" started-at="2019-12-25T05:20:48Z" finished-at="2019-12-25T05:21:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addNewCustomer()[pri:0, instance:com.inetBankingV1.testcases.TC_AddCustomer_003@dd8ba08]" name="addNewCustomer" duration-ms="22" started-at="2019-12-25T05:21:02Z" finished-at="2019-12-25T05:21:02Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.inetBankingV1.testcases.TC_AddCustomer_003.addNewCustomer(TC_AddCustomer_003.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.inetBankingV1.testcases.TC_AddCustomer_003@dd8ba08]" name="tearDown" is-config="true" duration-ms="730" started-at="2019-12-25T05:21:03Z" finished-at="2019-12-25T05:21:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.inetBankingV1.testcases.TC_AddCustomer_003 -->
      <class name="com.inetBankingV1.testcases.TC_LoginDp_002">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.inetBankingV1.testcases.TC_LoginDp_002@245b4bdc]" name="setUp" is-config="true" duration-ms="5487" started-at="2019-12-25T05:21:03Z" finished-at="2019-12-25T05:21:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginDp(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV1.testcases.TC_LoginDp_002@245b4bdc]" name="loginDp" duration-ms="4" started-at="2019-12-25T05:21:09Z" data-provider="getData" finished-at="2019-12-25T05:21:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr23909]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[YtAmup]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.inetBankingV1.testcases.TC_LoginDp_002.loginDp(TC_LoginDp_002.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.inetBankingV1.testcases.TC_LoginDp_002@245b4bdc]" name="tearDown" is-config="true" duration-ms="667" started-at="2019-12-25T05:21:09Z" finished-at="2019-12-25T05:21:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.inetBankingV1.testcases.TC_LoginDp_002 -->
    </test> <!-- Test(failed) -->
  </suite> <!-- Failed suite [Suite] -->
</testng-results>
